#!/bin/bash

if [[ $# -ne 1 ]]
then
    echo "usage: $0 \"filename.ext\""
    echo "Returns filename's extension"
    echo "Note: it applies basename before"
    exit 2
fi

BASENAME="$(basename "$1")"
EXTENSION="${BASENAME##*.}"
FILENAME="${BASENAME%.*}"

echo "${EXTENSION}"
exit 0